#!/usr/bin/env bash

# $1 is dwarf++.hh
# $2 is data.hh
# $3 is to_string.cc

(
echo "// Automatically generated by make at $(date)"
echo "// DO NOT EDIT"
echo
echo '#include "internal.hh"'
echo
echo DWARFPP_BEGIN_NAMESPACE
echo

python3 ${CMAKE_CURRENT_LIST_DIR}/../elf/enum-print.py < $1
python3 ${CMAKE_CURRENT_LIST_DIR}/../elf/enum-print.py -s _ -u --hex -x hi_user -x lo_user < $2

echo DWARFPP_END_NAMESPACE
) > $3
