#!/usr/bin/env bash

(
echo "// Automatically generated by make at $(date)"
echo "// DO NOT EDIT"
echo
echo '#include "data.hh"'
echo '#include "to_hex.hh"'
echo
echo 'ELFPP_BEGIN_NAMESPACE'
echo

python3 ${CMAKE_CURRENT_LIST_DIR}/enum-print.py -u --hex --no-type --mask shf --mask pf \
    -x loos -x hios -x loproc -x hiproc < $1

echo ELFPP_END_NAMESPACE
) > $2
