#!/usr/bin/env bash

OUTFILE=$1

cd $(dirname $0)

echo "// Automatically generated by cmake on $(date)" >$OUTFILE
echo "// DO NOT EDIT" >>$OUTFILE
echo >>$OUTFILE
echo '#include "data.hh"' >>$OUTFILE
echo '#include "to_hex.hh"' >>$OUTFILE
echo >>$OUTFILE
echo 'ELFPP_BEGIN_NAMESPACE' >>$OUTFILE
echo >>$OUTFILE
python3 enum-print.py -u --hex --no-type --mask shf --mask pf \
  -x loos -x hios -x loproc -x hiproc <data.hh >>$OUTFILE
echo 'ELFPP_END_NAMESPACE' >>$OUTFILE
